### ISSUE TITLE
TypeError: Cannot read property 'owner' of null

### ISSUE THREAD

**Issue by phun-ky** [jonschlinkert/pkg-homepage#1]
Don't know if this is the right repo (you have so many 😁 ), but suddenly when running:

    verb --no-reflinks-cache

To generate the readme (worked fine yesterday), I get this error:

    TypeError: Cannot read property 'owner' of null
        at Function.module.exports (/usr/lib/node_modules/verb-generate-readme/node_modules/pkg-homepage/index.js:31:32)
        at /usr/lib/node_modules/verb-generate-readme/node_modules/reflinks/index.js:116:26
        at Array.reduce (native)
        at linkify (/usr/lib/node_modules/verb-generate-readme/node_modules/reflinks/index.js:113:30)
        at /usr/lib/node_modules/verb-generate-readme/node_modules/reflinks/index.js:93:17
        at /usr/lib/node_modules/verb-generate-readme/node_modules/async-each/index.js:24:44
        at /usr/lib/node_modules/verb-generate-readme/node_modules/reflinks/index.js:73:7
        at /usr/lib/node_modules/verb-generate-readme/node_modules/get-pkg/index.js:43:5
        at IncomingMessage.<anonymous> (/usr/lib/node_modules/verb-generate-readme/node_modules/min-request/request.js:68:4)
        at emitNone (events.js:91:20)

And I think the reason for this, is that I see in `get-pkg`, when querying the registry for packages, a package emerges with no `repository` field: (This package is not in my project, so why is it even queryied for?)

    ⠋ creating reference links from npm datapatch function (err, pkg) {
          if (err) {
            if (err.message === 'document not found') {
              dates.set(name, {});
              next();
              return;
            }
            next(err);
            return;
          }

          dates.set(name, pkg);
          store.set(name, pkg);
          pkgs.push(pkg);
          next();
        }
    ⠙ creating reference links from npm data{ name: 'patch',
      version: '0.0.1',
      description: 'an object patching tool',
      main: 'patch.js',
      directories: { test: 'tests' },
      dependencies: {},
      devDependencies: { specify: '~1.1.2' },
      scripts: { test: 'node tests/*.js' },
      repository: '',
      author: { name: 'john chesley', email: 'john@chesl.es' },
      license: 'MIT',
      _id: 'patch@0.0.1',
      dist:
       { shasum: '293056dbbc71c979a1b7273308b12c5460246833',
         tarball: 'http://registry.npmjs.org/patch/-/patch-0.0.1.tgz' },
      _npmVersion: '1.1.65',
      _npmUser: { name: 'chesles', email: 'john@chesl.es' },
      maintainers: [ { name: 'chesles', email: 'john@chesl.es' } ] }
    [ { name: 'patch',
        version: '0.0.1',
        description: 'an object patching tool',
        main: 'patch.js',
        directories: { test: 'tests' },
        dependencies: {},
        devDependencies: { specify: '~1.1.2' },
        scripts: { test: 'node tests/*.js' },
        repository: '',
        author: { name: 'john chesley', email: 'john@chesl.es' },
        license: 'MIT',
        _id: 'patch@0.0.1',
        dist:
         { shasum: '293056dbbc71c979a1b7273308b12c5460246833',
           tarball: 'http://registry.npmjs.org/patch/-/patch-0.0.1.tgz' },
        _npmVersion: '1.1.65',
        _npmUser: { name: 'chesles', email: 'john@chesl.es' },
        maintainers: [ [Object] ] } ] { lookup: [Function],
      toAlias: [Function],
      help: { command: 'verb', configname: 'verbfile', appname: 'verb' },
      _: [],
      diff: false,
      diffOnly: false,
      'reflinks-cache': false,
      reflinksCache: false,
      cwd: '/mnt/c/Users/v6a.EUROPE/Workspace/my-project-frontend',
      tasks: [ 'readme' ],
      toc:
       { render: true,
         footer: '\n\n_(TOC generated by [verb](https://github.com/verbose/verb) using [markdown-toc](https://github.com/jonschlinkert/markdown-toc))_',
         linkify: [Function],
         method: 'postLayout' },
      engineOpts: { delims: [ '{%', '%}' ] },
      renameKey: [Function],
      cache: false }

Output when only running `verb`:

    [ { name: 'patch',
        version: '0.0.1',
        description: 'an object patching tool',
        main: 'patch.js',
        directories: { test: 'tests' },
        dependencies: {},
        devDependencies: { specify: '~1.1.2' },
        scripts: { test: 'node tests/*.js' },
        repository: '',
        author: { name: 'john chesley', email: 'john@chesl.es' },
        license: 'MIT',
        _id: 'patch@0.0.1',
        dist:
         { shasum: '293056dbbc71c979a1b7273308b12c5460246833',
           tarball: 'http://registry.npmjs.org/patch/-/patch-0.0.1.tgz' },
        _npmVersion: '1.1.65',
        _npmUser: { name: 'chesles', email: 'john@chesl.es' },
        maintainers: [ [Object] ] } ] { lookup: [Function],
      toAlias: [Function],
      help: { command: 'verb', configname: 'verbfile', appname: 'verb' },
      _: [],
      diff: false,
      diffOnly: false,
      cwd: '/mnt/c/Users/v6a.EUROPE/Workspace/my-project-frontend',
      tasks: [ 'readme' ],
      toc:
       { render: true,
         footer: '\n\n_(TOC generated by [verb](https://github.com/verbose/verb) using [markdown-toc](https://github.com/jonschlinkert/markdown-toc))_',
         linkify: [Function],
         method: 'postLayout' },
      engineOpts: { delims: [ '{%', '%}' ] },
      renameKey: [Function] }

    ---------------------

    TypeError: Cannot read property 'owner' of null
        at Function.module.exports (/usr/lib/node_modules/verb-generate-readme/node_modules/pkg-homepage/index.js:31:32)
        at /usr/lib/node_modules/verb-generate-readme/node_modules/reflinks/index.js:116:26
        at Array.reduce (native)
        at linkify (/usr/lib/node_modules/verb-generate-readme/node_modules/reflinks/index.js:113:30)
        at /usr/lib/node_modules/verb-generate-readme/node_modules/reflinks/index.js:93:17
        at /usr/lib/node_modules/verb-generate-readme/node_modules/async-each/index.js:24:44
        at /usr/lib/node_modules/verb-generate-readme/node_modules/reflinks/index.js:54:9
        at /usr/lib/node_modules/verb-generate-readme/node_modules/async-each/index.js:16:7
        at Array.forEach (native)
        at Function.each (/usr/lib/node_modules/verb-generate-readme/node_modules/async-each/index.js:15:11)

**Comment by jonschlinkert** [comment]
thanks for the investigative work! I appreciate it! I'll look into it and see if I can track it down
